# Site settings
title: "Nicholas Qiu's Tech Notes"
email: icutecapricorn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Accept the things you cannot change.
  Have the courage to change the things you can.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/NicholasQiu" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  NicholasQiu

# Build settings
markdown: kramdown
